
// Simulate Database JSON API responses with parsed JS objects in the format I would 
// generally expect a server to respond with (of course that would depend on the paricular data represented)
// 
// For the basic example of this App, I assume all ingredients have a name, amount, and unit
// It would be easy to generalize this to different details for each ingredient in the general case
var hops = [
{name: "Ahtanum", amount: 0, unit: 'lb'}, 
{name: "Amarillo", amount: 0, unit: 'lb'},
{name: "Cascade", amount: 0, unit: 'lb'},
{name: "Centennial", amount: 0, unit: 'lb'},
{name: "Chinook", amount: 0, unit: 'lb'},
{name: "Columbus", amount: 0, unit: 'lb'},
{name: "Cluster", amount: 0, unit: 'lb'},
{name: "Crystal", amount: 0, unit: 'lb'},
{name: "Fuggle", amount: 0, unit: 'lb'}, 
{name: "Galena", amount: 0, unit: 'lb'},
{name: "Golding", amount: 0, unit: 'lb'},
{name: "Hallertau mf", amount: 0, unit: 'lb'},
{name: "Horizon", amount: 0, unit: 'lb'},
{name: "Liberty", amount: 0, unit: 'lb'},
{name: "Magnum", amount: 0, unit: 'lb'},
{name: "Northern Brewer", amount: 0, unit: 'lb'},
{name: "Nugget", amount: 0, unit: 'lb'},
{name: "Perle", amount: 0, unit: 'lb'},
{name: "Saaz", amount: 0, unit: 'lb'},
{name: "Satus", amount: 0, unit: 'lb'},
{name: "Spalt Select", amount: 0, unit: 'lb'},
{name: "Sterling", amount: 0, unit: 'lb'},
{name: "Tettnang", amount: 0, unit: 'lb'},
{name: "Tomahawk", amount: 0, unit: 'lb'},
{name: "Ultra", amount: 0, unit: 'lb'},
{name: "US Fuggle", amount: 0, unit: 'lb'},
{name: "Vanguard", amount: 0, unit: 'lb'},
{name: "Warrior", amount: 0, unit: 'lb'},
{name: "Willamette", amount: 0, unit: 'lb'},
];

var yeast = [ { name: 'California Ale Yeast®', amount: 0, unit: 'lb' },
  { name: 'English Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'German Ale II', amount: 0, unit: 'lb' },
  { name: 'Irish Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'British Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Bedford British', amount: 0, unit: 'lb' },
  { name: 'Dry English Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'East Coast Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Australian Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'European Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'London Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Whitbread Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Essex Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Burton Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Edinburgh Scottish Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'German Ale/ Kölsch Yeast', amount: 0, unit: 'lb' },
  { name: 'Dusseldorf Alt Yeast', amount: 0, unit: 'lb' },
  { name: 'Yorkshire Square Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'East Midlands Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Pacific Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Scotch Whisky Yeast', amount: 0, unit: 'lb' },
  { name: 'Tennessee Whiskey Yeast', amount: 0, unit: 'lb' },
  { name: 'California Ale V Yeast', amount: 0, unit: 'lb' },
  { name: 'American Ale Yeast Blend', amount: 0, unit: 'lb' },
  { name: 'American Whiskey Yeast', amount: 0, unit: 'lb' },
  { name: 'Bourbon Yeast', amount: 0, unit: 'lb' },
  { name: 'French Ale', amount: 0, unit: 'lb' },
  { name: 'Neutral Grain Yeast', amount: 0, unit: 'lb' },
  { name: 'Cream Ale Yeast Blend', amount: 0, unit: 'lb' },
  { name: 'English Ale Blend', amount: 0, unit: 'lb' },
  { name: 'San Diego Super Yeast', amount: 0, unit: 'lb' },
  { name: 'Burlington Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Super High Gravity Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Hefeweizen Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'American Hefeweizen Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Bavarian Weizen Yeast', amount: 0, unit: 'lb' },
  { name: 'Hefeweizen IV Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Wit Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Wit II Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Monastery Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Bastogne Belgian Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Antwerp Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Abbey Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Abbey IV Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Strong Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Saison I Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Saison II Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Style Saison Ale Yeast Blend',
    amount: 0,
    unit: 'lb' },
  { name: 'Belgian Golden Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Belgian Style Ale Yeast Blend', amount: 0, unit: 'lb' },
  { name: 'Belgian Saison III Yeast', amount: 0, unit: 'lb' },
  { name: 'French Saison Ale Yeast', amount: 0, unit: 'lb' },
  { name: 'Berliner Weisse Blend', amount: 0, unit: 'lb' },
  { name: 'Saccharomyces Trois', amount: 0, unit: 'lb' },
  { name: 'Brettanomyces claussenii', amount: 0, unit: 'lb' },
  { name: 'Brettanomyces bruxellensis Trois Vrai',
    amount: 0,
    unit: 'lb' },
  { name: 'Brettanomyces bruxellensis', amount: 0, unit: 'lb' },
  { name: 'Brettanomyces lambicus', amount: 0, unit: 'lb' },
  { name: 'Belgian Sour Mix 1', amount: 0, unit: 'lb' },
  { name: 'Pediococcus damnosus', amount: 0, unit: 'lb' },
  { name: 'Flemish Ale Blend', amount: 0, unit: 'lb' },
  { name: 'American Farmhouse Blend', amount: 0, unit: 'lb' },
  { name: 'Lactobacillus brevis', amount: 0, unit: 'lb' },
  { name: 'Malolactic Cultures', amount: 0, unit: 'lb' },
  { name: 'Lactobacillus delbrueckii Bacteria',
    amount: 0,
    unit: 'lb' },
  { name: 'Flor Sherrry Yeast', amount: 0, unit: 'lb' },
  { name: 'Sake Yeast', amount: 0, unit: 'lb' },
  { name: 'California Pinot Noir Yeast', amount: 0, unit: 'lb' },
  { name: 'Sake #9 Yeast', amount: 0, unit: 'lb' },
  { name: 'Champagne Yeast', amount: 0, unit: 'lb' },
  { name: 'Avize Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'Sweet Mead/Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'Steinberg-Geisenheim Wine Yeast',
    amount: 0,
    unit: 'lb' },
  { name: 'Chardonnay White Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'French White Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'Merlot Red Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'Assmanshausen Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'French Red Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'Cabernet Red Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'Suremain Burgundy Wine Yeast', amount: 0, unit: 'lb' },
  { name: 'English Cider Yeast', amount: 0, unit: 'lb' },
  { name: 'Pilsner Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'Czech Budejovice Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'San Francisco Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'Oktoberfest/Märzen Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'German Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'German Bock Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'German Lager X', amount: 0, unit: 'lb' },
  { name: 'Southern German Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'American Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'Munich Helles Yeast', amount: 0, unit: 'lb' },
  { name: 'Cry Havoc', amount: 0, unit: 'lb' },
  { name: 'Zurich Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'Old Bavarian Lager Yeast', amount: 0, unit: 'lb' },
  { name: 'Mexican Lager Yeast', amount: 0, unit: 'lb' } ];


var fermentables = [ 
  { name: 'Recipes', amount: 0, unit: 'lb' },
  { name: 'Abbey Malt', amount: 0, unit: 'lb' },
  { name: 'Acidulated Malt', amount: 0, unit: 'lb' },
  { name: 'Amber', amount: 0, unit: 'lb' },
  { name: 'Apricot', amount: 0, unit: 'lb' },
  { name: 'Aromatic', amount: 0, unit: 'lb' },
  { name: 'Aromatic Malt', amount: 0, unit: 'lb' },
  { name: 'Ashbourne Mild', amount: 0, unit: 'lb' },
  { name: 'Banana', amount: 0, unit: 'lb' },
  { name: 'Belgian Candi Sugar - Amber/Brown',
    amount: 0,
    unit: 'lb' },
  { name: 'Belgian Candi Sugar - Clear/Blond',
    amount: 0,
    unit: 'lb' },
  { name: 'Belgian Candi Sugar - Dark', amount: 0, unit: 'lb' },
  { name: 'Belgian Candi Syrup - Amber', amount: 0, unit: 'lb' },
  { name: 'Belgian Candi Syrup - Clear', amount: 0, unit: 'lb' },
  { name: 'Belgian Candi Syrup - D2', amount: 0, unit: 'lb' },
  { name: 'Belgian Candi Syrup - Dark', amount: 0, unit: 'lb' },
  { name: 'Biscuit', amount: 0, unit: 'lb' },
  { name: 'Black Barley', amount: 0, unit: 'lb' },
  { name: 'Black Malt', amount: 0, unit: 'lb' },
  { name: 'Black Patent', amount: 0, unit: 'lb' },
  { name: 'Blackprinz', amount: 0, unit: 'lb' },
  { name: 'Blueberry', amount: 0, unit: 'lb' },
  { name: 'Bohemian Pilsner', amount: 0, unit: 'lb' },
  { name: 'Bonlander Munich', amount: 0, unit: 'lb' },
  { name: 'Brown', amount: 0, unit: 'lb' },
  { name: 'Brown Rice Syrup - Gluten Free', amount: 0, unit: 'lb' },
  { name: 'Brown Sugar', amount: 0, unit: 'lb' },
  { name: 'Buckwheat Malt - Gluten Free', amount: 0, unit: 'lb' },
  { name: 'Cane Sugar', amount: 0, unit: 'lb' },
  { name: 'Cara 20L', amount: 0, unit: 'lb' },
  { name: 'Cara 45L', amount: 0, unit: 'lb' },
  { name: 'Cara Malt', amount: 0, unit: 'lb' },
  { name: 'Cara Pale', amount: 0, unit: 'lb' },
  { name: 'Cara Plus 100', amount: 0, unit: 'lb' },
  { name: 'Cara Plus 150', amount: 0, unit: 'lb' },
  { name: 'Cara Plus 200', amount: 0, unit: 'lb' },
  { name: 'Cara Plus 250', amount: 0, unit: 'lb' },
  { name: 'CaraAmber', amount: 0, unit: 'lb' },
  { name: 'CaraAroma', amount: 0, unit: 'lb' },
  { name: 'CaraBelge', amount: 0, unit: 'lb' },
  { name: 'CaraBohemian', amount: 0, unit: 'lb' },
  { name: 'CaraBrown', amount: 0, unit: 'lb' },
  { name: 'CaraCrystal Wheat Malt', amount: 0, unit: 'lb' },
  { name: 'Carafa I', amount: 0, unit: 'lb' },
  { name: 'Carafa II', amount: 0, unit: 'lb' },
  { name: 'Carafa III', amount: 0, unit: 'lb' },
  { name: 'CaraFoam', amount: 0, unit: 'lb' },
  { name: 'CaraHell', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 10L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 120L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 150L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 15L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 20L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 30L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 40L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 60L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 75L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 80L', amount: 0, unit: 'lb' },
  { name: 'Caramel / Crystal 90L', amount: 0, unit: 'lb' },
  { name: 'Caramel Pils', amount: 0, unit: 'lb' },
  { name: 'Caramel Wheat', amount: 0, unit: 'lb' },
  { name: 'CaraMunich', amount: 0, unit: 'lb' },
  { name: 'CaraMunich I', amount: 0, unit: 'lb' },
  { name: 'CaraMunich II', amount: 0, unit: 'lb' },
  { name: 'CaraMunich III', amount: 0, unit: 'lb' },
  { name: 'Carapils', amount: 0, unit: 'lb' },
  { name: 'Carapils (Dextrine Malt)', amount: 0, unit: 'lb' },
  { name: 'CaraRed', amount: 0, unit: 'lb' },
  { name: 'Carastan (30/37)', amount: 0, unit: 'lb' },
  { name: 'Carastan Light (15L)', amount: 0, unit: 'lb' },
  { name: 'CaraVienne', amount: 0, unit: 'lb' },
  { name: 'Cherry', amount: 0, unit: 'lb' },
  { name: 'Chocolate', amount: 0, unit: 'lb' },
  { name: 'Chocolate Malt', amount: 0, unit: 'lb' },
  { name: 'Chocolate Rye', amount: 0, unit: 'lb' },
  { name: 'Chocolate Wheat', amount: 0, unit: 'lb' },
  { name: 'Coffee Malt', amount: 0, unit: 'lb' },
  { name: 'Cookie Malt', amount: 0, unit: 'lb' },
  { name: 'Corn Sugar - Dextrose', amount: 0, unit: 'lb' },
  { name: 'Corn Syrup', amount: 0, unit: 'lb' },
  { name: 'Cranberry', amount: 0, unit: 'lb' },
  { name: 'Crystal 10L Millet Malt - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'Crystal 140L', amount: 0, unit: 'lb' },
  { name: 'Crystal 15L', amount: 0, unit: 'lb' },
  { name: 'Crystal 30L', amount: 0, unit: 'lb' },
  { name: 'Crystal 30L Millet Malt - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'Crystal 45L', amount: 0, unit: 'lb' },
  { name: 'Crystal 50L', amount: 0, unit: 'lb' },
  { name: 'Crystal 60L', amount: 0, unit: 'lb' },
  { name: 'Crystal 70L', amount: 0, unit: 'lb' },
  { name: 'Crystal 90L', amount: 0, unit: 'lb' },
  { name: 'Crystal Malt 100', amount: 0, unit: 'lb' },
  { name: 'Crystal Malt 150', amount: 0, unit: 'lb' },
  { name: 'Crystal Malt 250', amount: 0, unit: 'lb' },
  { name: 'Crystal Malt 300', amount: 0, unit: 'lb' },
  { name: 'Crystal Malt 50', amount: 0, unit: 'lb' },
  { name: 'Crystal Rye', amount: 0, unit: 'lb' },
  { name: 'Dark Ale', amount: 0, unit: 'lb' },
  { name: 'Dark Chocolate', amount: 0, unit: 'lb' },
  { name: 'Dark Crystal 80L', amount: 0, unit: 'lb' },
  { name: 'Dark Munich', amount: 0, unit: 'lb' },
  { name: 'Dark Roasted Millet Malt - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'Dark Wheat', amount: 0, unit: 'lb' },
  { name: 'Date', amount: 0, unit: 'lb' },
  { name: 'De-Bittered Black', amount: 0, unit: 'lb' },
  { name: 'De-Husked Caraf I', amount: 0, unit: 'lb' },
  { name: 'De-Husked Caraf II', amount: 0, unit: 'lb' },
  { name: 'De-Husked Caraf III', amount: 0, unit: 'lb' },
  { name: 'Dextrine Malt', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Amber', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Dark', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Extra Light', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Light', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Munich', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Pilsen', amount: 0, unit: 'lb' },
  { name: 'Dry Malt Extract - Wheat', amount: 0, unit: 'lb' },
  { name: 'Enzyme Malt', amount: 0, unit: 'lb' },
  { name: 'ESB Malt', amount: 0, unit: 'lb' },
  { name: 'Extra Dark Crystal 120L', amount: 0, unit: 'lb' },
  { name: 'Extra Dark Crystal 160L', amount: 0, unit: 'lb' },
  { name: 'Flaked Barley', amount: 0, unit: 'lb' },
  { name: 'Flaked Corn', amount: 0, unit: 'lb' },
  { name: 'Flaked Oats', amount: 0, unit: 'lb' },
  { name: 'Flaked Rice', amount: 0, unit: 'lb' },
  { name: 'Flaked Rye', amount: 0, unit: 'lb' },
  { name: 'Flaked Wheat', amount: 0, unit: 'lb' },
  { name: 'Floor-Malted Bohemian Pilsner', amount: 0, unit: 'lb' },
  { name: 'Floor-Malted Bohemian Pilsner Dk',
    amount: 0,
    unit: 'lb' },
  { name: 'Floor-Malted Bohemian Wheat', amount: 0, unit: 'lb' },
  { name: 'Golden Naked Oats', amount: 0, unit: 'lb' },
  { name: 'Golden Promise', amount: 0, unit: 'lb' },
  { name: 'Gooseberry', amount: 0, unit: 'lb' },
  { name: 'Grits', amount: 0, unit: 'lb' },
  { name: 'Halcyon', amount: 0, unit: 'lb' },
  { name: 'Honey', amount: 0, unit: 'lb' },
  { name: 'Honey (Buckwheat)', amount: 0, unit: 'lb' },
  { name: 'Honey Malt', amount: 0, unit: 'lb' },
  { name: 'Invert Sugar', amount: 0, unit: 'lb' },
  { name: 'Kölsch', amount: 0, unit: 'lb' },
  { name: 'Lactose (Milk Sugar)', amount: 0, unit: 'lb' },
  { name: 'Lager', amount: 0, unit: 'lb' },
  { name: 'Light Roasted Millet Malt - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'Lime', amount: 0, unit: 'lb' },
  { name: 'Liquid Malt Extract - Amber', amount: 0, unit: 'lb' },
  { name: 'Liquid Malt Extract - Dark', amount: 0, unit: 'lb' },
  { name: 'Liquid Malt Extract - Extra Light',
    amount: 0,
    unit: 'lb' },
  { name: 'Liquid Malt Extract - Light', amount: 0, unit: 'lb' },
  { name: 'Liquid Malt Extract - Munich', amount: 0, unit: 'lb' },
  { name: 'Liquid Malt Extract - Pilsen', amount: 0, unit: 'lb' },
  { name: 'Liquid Malt Extract - Wheat', amount: 0, unit: 'lb' },
  { name: 'Malted Naked Oats', amount: 0, unit: 'lb' },
  { name: 'Maltodextrin', amount: 0, unit: 'lb' },
  { name: 'Mango', amount: 0, unit: 'lb' },
  { name: 'Maple Syrup', amount: 0, unit: 'lb' },
  { name: 'Maris Otter Pale', amount: 0, unit: 'lb' },
  { name: 'Medium Roasted Millet Malt - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'Melanoid Malt', amount: 0, unit: 'lb' },
  { name: 'Melanoidin', amount: 0, unit: 'lb' },
  { name: 'Midnight Wheat Malt', amount: 0, unit: 'lb' },
  { name: 'Mild', amount: 0, unit: 'lb' },
  { name: 'Molasses', amount: 0, unit: 'lb' },
  { name: 'Munich', amount: 0, unit: 'lb' },
  { name: 'Munich - 60L', amount: 0, unit: 'lb' },
  { name: 'Munich - Dark 20L', amount: 0, unit: 'lb' },
  { name: 'Munich - Light 10L', amount: 0, unit: 'lb' },
  { name: 'Munich Dark', amount: 0, unit: 'lb' },
  { name: 'Munich Light', amount: 0, unit: 'lb' },
  { name: 'Munich Malt', amount: 0, unit: 'lb' },
  { name: 'Munich Millet Malt - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'Oat Malt', amount: 0, unit: 'lb' },
  { name: 'Optic', amount: 0, unit: 'lb' },
  { name: 'Organic Pilsner Malt', amount: 0, unit: 'lb' },
  { name: 'Pale 2-Row', amount: 0, unit: 'lb' },
  { name: 'Pale 2-Row - Toasted', amount: 0, unit: 'lb' },
  { name: 'Pale 6-Row', amount: 0, unit: 'lb' },
  { name: 'Pale Ale', amount: 0, unit: 'lb' },
  { name: 'Pale Ale Malt', amount: 0, unit: 'lb' },
  { name: 'Pale Chocolate', amount: 0, unit: 'lb' },
  { name: 'Pale Millet Malt - Gluten Free', amount: 0, unit: 'lb' },
  { name: 'Pale Wheat', amount: 0, unit: 'lb' },
  { name: 'Peach', amount: 0, unit: 'lb' },
  { name: 'Pear', amount: 0, unit: 'lb' },
  { name: 'Pearl', amount: 0, unit: 'lb' },
  { name: 'Peated Malt', amount: 0, unit: 'lb' },
  { name: 'Pilsen', amount: 0, unit: 'lb' },
  { name: 'Pilsner', amount: 0, unit: 'lb' },
  { name: 'Pilsner Malt', amount: 0, unit: 'lb' },
  { name: 'Pineapple', amount: 0, unit: 'lb' },
  { name: 'Plum', amount: 0, unit: 'lb' },
  { name: 'Raspberry', amount: 0, unit: 'lb' },
  { name: 'Red Wheat', amount: 0, unit: 'lb' },
  { name: 'Red X', amount: 0, unit: 'lb' },
  { name: 'Rice Hulls', amount: 0, unit: 'lb' },
  { name: 'Rice Syrup Solids', amount: 0, unit: 'lb' },
  { name: 'Roasted Barley', amount: 0, unit: 'lb' },
  { name: 'Rolled Oats', amount: 0, unit: 'lb' },
  { name: 'Rye', amount: 0, unit: 'lb' },
  { name: 'Smoked Malt', amount: 0, unit: 'lb' },
  { name: 'Soft Candi Sugar - Blond', amount: 0, unit: 'lb' },
  { name: 'Soft Candi Sugar - Brown', amount: 0, unit: 'lb' },
  { name: 'Special B', amount: 0, unit: 'lb' },
  { name: 'Special Roast', amount: 0, unit: 'lb' },
  { name: 'Spelt Malt', amount: 0, unit: 'lb' },
  { name: 'Strawberry', amount: 0, unit: 'lb' },
  { name: 'Torrified Barley', amount: 0, unit: 'lb' },
  { name: 'Torrified Wheat', amount: 0, unit: 'lb' },
  { name: 'Turbinado', amount: 0, unit: 'lb' },
  { name: 'Unmalted Wheat', amount: 0, unit: 'lb' },
  { name: 'Victory', amount: 0, unit: 'lb' },
  { name: 'Vienna', amount: 0, unit: 'lb' },
  { name: 'Vienna Malt', amount: 0, unit: 'lb' },
  { name: 'Watermelon', amount: 0, unit: 'lb' },
  { name: 'Wheat', amount: 0, unit: 'lb' },
  { name: 'Wheat Malt', amount: 0, unit: 'lb' },
  { name: 'White Sorghum Syrup - Gluten Free',
    amount: 0,
    unit: 'lb' },
  { name: 'White Wheat', amount: 0, unit: 'lb' } ]

var extras = [ { name: 'Allspice', amount: 0, unit: 'lb' },
  { name: 'Allspice Powder', amount: 0, unit: 'lb' },
  { name: 'American Oak Chips', amount: 0, unit: 'lb' },
  { name: 'American Oak Cubes (Heavy Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'American Oak Cubes (Medium-Heavy Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'American Oak Cubes (Medium Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'American Oak Spiral (Heavy Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'American Oak Spiral (Light Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'American Oak Spiral (Medium Plus Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'American Oak Spiral (Medium Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'Amylase Enzyme', amount: 0, unit: 'lb' },
  { name: 'Apple Extract', amount: 0, unit: 'lb' },
  { name: 'Apricot Extract', amount: 0, unit: 'lb' },
  { name: 'Apricot Puree', amount: 0, unit: 'lb' },
  { name: 'Banana Extract', amount: 0, unit: 'lb' },
  { name: 'Bitter Orange Peel', amount: 0, unit: 'lb' },
  { name: 'Blackberries (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Blackberries (Frozen)', amount: 0, unit: 'lb' },
  { name: 'Blackberry Extract', amount: 0, unit: 'lb' },
  { name: 'Blackberry Puree', amount: 0, unit: 'lb' },
  { name: 'Black Currant Extract', amount: 0, unit: 'lb' },
  { name: 'Black Pepper', amount: 0, unit: 'lb' },
  { name: 'Black Pepper (Ground)', amount: 0, unit: 'lb' },
  { name: 'Black Pepper (Whole)', amount: 0, unit: 'lb' },
  { name: 'Blueberries (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Blueberries (Frozen)', amount: 0, unit: 'lb' },
  { name: 'Blueberry Puree', amount: 0, unit: 'lb' },
  { name: 'Bourbon', amount: 0, unit: 'lb' },
  { name: 'Bourbon Soaked French Oak Chips',
    amount: 0,
    unit: 'lb' },
  { name: 'BrewVint Yeast Nutrient', amount: 0, unit: 'lb' },
  { name: 'Burton Water Salts', amount: 0, unit: 'lb' },
  { name: 'Calcium Carbonate', amount: 0, unit: 'lb' },
  { name: 'Calcium Chloride', amount: 0, unit: 'lb' },
  { name: 'Campden Tablet', amount: 0, unit: 'lb' },
  { name: 'Cardamom (Ground)', amount: 0, unit: 'lb' },
  { name: 'Cardamom Seed', amount: 0, unit: 'lb' },
  { name: 'Cardamom (Whole)', amount: 0, unit: 'lb' },
  { name: 'Chamomile (Dried)', amount: 0, unit: 'lb' },
  { name: 'Chamomile (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Cherries', amount: 0, unit: 'lb' },
  { name: 'Cherry Extract', amount: 0, unit: 'lb' },
  { name: 'Cherry Puree', amount: 0, unit: 'lb' },
  { name: 'Chicory Root', amount: 0, unit: 'lb' },
  { name: 'Chipotle Chili', amount: 0, unit: 'lb' },
  { name: 'Chocolate (Dark)', amount: 0, unit: 'lb' },
  { name: 'Chocolate Extract', amount: 0, unit: 'lb' },
  { name: 'Chocolate (Milk)', amount: 0, unit: 'lb' },
  { name: 'Cinnamon (Ground)', amount: 0, unit: 'lb' },
  { name: 'Cinnamon Sticks', amount: 0, unit: 'lb' },
  { name: 'Cocoa Nibs', amount: 0, unit: 'lb' },
  { name: 'Cocoa Powder', amount: 0, unit: 'lb' },
  { name: 'Coffee (Brewed)', amount: 0, unit: 'lb' },
  { name: 'Coffee (Ground)', amount: 0, unit: 'lb' },
  { name: 'Coriander Seed', amount: 0, unit: 'lb' },
  { name: 'Cranberry Extract', amount: 0, unit: 'lb' },
  { name: 'Dextrose', amount: 0, unit: 'lb' },
  { name: 'Dried Woodruff', amount: 0, unit: 'lb' },
  { name: 'Elderflowers (Dried)', amount: 0, unit: 'lb' },
  { name: 'Epsom Salt (MgSO4)', amount: 0, unit: 'lb' },
  { name: 'Espresso', amount: 0, unit: 'lb' },
  { name: 'Fermax Yeast Nutrient', amount: 0, unit: 'lb' },
  { name: 'Five Star 5.2 pH Stabilizer', amount: 0, unit: 'lb' },
  { name: 'French Oak Chips', amount: 0, unit: 'lb' },
  { name: 'French Oak Cubes (Heavy Toast)', amount: 0, unit: 'lb' },
  { name: 'French Oak Cubes (Medium-Heavy Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'French Oak Cubes (Medium Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'French Oak Spiral (Heavy Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'French Oak Spiral (Light Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'French Oak Spiral (Medium Plus Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'French Oak Spiral (Medium Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'Gelatin', amount: 0, unit: 'lb' },
  { name: 'Ginger Extract', amount: 0, unit: 'lb' },
  { name: 'Ginger Root (Dried)', amount: 0, unit: 'lb' },
  { name: 'Ginger Root (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Grains of Paradise', amount: 0, unit: 'lb' },
  { name: 'Grape Extract', amount: 0, unit: 'lb' },
  { name: 'Grapefruit Zest', amount: 0, unit: 'lb' },
  { name: 'Gypsum (Calcium Sulfate)', amount: 0, unit: 'lb' },
  { name: 'Heather Tips', amount: 0, unit: 'lb' },
  { name: 'Hibiscus', amount: 0, unit: 'lb' },
  { name: 'Hungarian Oak Cubes (Medium Toast)',
    amount: 0,
    unit: 'lb' },
  { name: 'Indian Sarsaparilla', amount: 0, unit: 'lb' },
  { name: 'Irish Moss', amount: 0, unit: 'lb' },
  { name: 'Juniper Berries (Dried)', amount: 0, unit: 'lb' },
  { name: 'Juniper Berries (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Lactose', amount: 0, unit: 'lb' },
  { name: 'Lavender', amount: 0, unit: 'lb' },
  { name: 'Lemongrass (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Lemon Peel', amount: 0, unit: 'lb' },
  { name: 'Lemon Peel (Dried)', amount: 0, unit: 'lb' },
  { name: 'Lemon Zest', amount: 0, unit: 'lb' },
  { name: 'Licorice Root', amount: 0, unit: 'lb' },
  { name: 'Licorice Stick', amount: 0, unit: 'lb' },
  { name: 'Lime Peel (Dried)', amount: 0, unit: 'lb' },
  { name: 'Lime Zest', amount: 0, unit: 'lb' },
  { name: 'Maltodextrin', amount: 0, unit: 'lb' },
  { name: 'Mango (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Mango (Frozen)', amount: 0, unit: 'lb' },
  { name: 'Mugwort (Dried)', amount: 0, unit: 'lb' },
  { name: 'Nutmeg (Ground)', amount: 0, unit: 'lb' },
  { name: 'Oak Chips (Light)', amount: 0, unit: 'lb' },
  { name: 'Orange Juice', amount: 0, unit: 'lb' },
  { name: 'Orange Peel', amount: 0, unit: 'lb' },
  { name: 'Orange Zest', amount: 0, unit: 'lb' },
  { name: 'Peaches (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Peaches (Frozen)', amount: 0, unit: 'lb' },
  { name: 'Peach Puree', amount: 0, unit: 'lb' },
  { name: 'Pumpkin Pie Spice', amount: 0, unit: 'lb' },
  { name: 'Pumpkin Puree', amount: 0, unit: 'lb' },
  { name: 'Raisins', amount: 0, unit: 'lb' },
  { name: 'Raspberry Extract', amount: 0, unit: 'lb' },
  { name: 'Raspberry Puree', amount: 0, unit: 'lb' },
  { name: 'Raspberry (Whole)', amount: 0, unit: 'lb' },
  { name: 'Rose Hips', amount: 0, unit: 'lb' },
  { name: 'Rosemary (Dried)', amount: 0, unit: 'lb' },
  { name: 'Rosemary (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Sage (Dried)', amount: 0, unit: 'lb' },
  { name: 'Sage (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Serrano Chili', amount: 0, unit: 'lb' },
  { name: 'Servomyces Yeast Nutrient', amount: 0, unit: 'lb' },
  { name: 'Sour Cherries (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Sour Cherries (Frozen)', amount: 0, unit: 'lb' },
  { name: 'Spearmint (Dried)', amount: 0, unit: 'lb' },
  { name: 'Spearmint (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Spruce Essence', amount: 0, unit: 'lb' },
  { name: 'Spruce Tips', amount: 0, unit: 'lb' },
  { name: 'Star Anise', amount: 0, unit: 'lb' },
  { name: 'Strawberries (Fresh)', amount: 0, unit: 'lb' },
  { name: 'Strawberries (Frozen)', amount: 0, unit: 'lb' },
  { name: 'Strawberry Extract', amount: 0, unit: 'lb' },
  { name: 'Super Moss HB', amount: 0, unit: 'lb' },
  { name: 'Sweet Orange Peel', amount: 0, unit: 'lb' },
  { name: 'Toasted Coconut', amount: 0, unit: 'lb' },
  { name: 'Vanilla Beans', amount: 0, unit: 'lb' },
  { name: 'Vanilla Extract', amount: 0, unit: 'lb' },
  { name: 'Watermelon Extract', amount: 0, unit: 'lb' },
  { name: 'Whirlfloc Tablet', amount: 0, unit: 'lb' },
  { name: 'Whiskey', amount: 0, unit: 'lb' },
  { name: 'Whole Cloves', amount: 0, unit: 'lb' },
  { name: 'Wintergreen Leaves', amount: 0, unit: 'lb' },
  { name: 'Wormwood (Dried)', amount: 0, unit: 'lb' },
  { name: 'Yeast Energizer', amount: 0, unit: 'lb' },
  { name: 'Yeast Nutrient (Wyeast)', amount: 0, unit: 'lb' } ]

module.exports = { hops: hops, yeast: yeast, fermentables: fermentables, extras: extras}
